### ISSUE TITLE
Error during installation on RasPi 4

### ISSUE THREAD

**Issue by Octenisept** [nuriel77/goshimmer-playbook#16]
Hello everyone,

I've just tried to set up a IOTA GOSHIMMER node with the GoShimmer Playbook. Unfortunately after executing 

`sudo bash -c "bash <(curl -s https://raw.githubusercontent.com/nuriel77/goshimmer-playbook/master/goshimmer_install.sh)"
`

and after some time during the installation it fails while trying to build the goshimmer image.

Attached you can find the error log file which has been created. Unfortunately I'm pretty bad in interpreting the error messages.

I'd be grateful for any help or tips provided on how to solve!

[goshimmer-playbook-202002102049.log](https://github.com/nuriel77/goshimmer-playbook/files/4187738/goshimmer-playbook-202002102049.log)

**Comment by nuriel77** [comment]
Hi @Octenisept 
There's a bug with 32 bit OS and building goshimmer (I think because of the DB component, there's an issue opened about it).

In any case I advise to use a 64 bit OS (with Raspbian you can enable it `arm_64bit = 1` I believe, see https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md or use Ubuntu 19, the 64 bit image: https://ubuntu.com/download/raspberry-pi)
